"""auto-generating tables

Revision ID: 4a4fb781cdd7
Revises: 
Create Date: 2025-02-27 13:27:51.863446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a4fb781cdd7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Routes',
    sa.Column('route_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('Users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('password')
    )
    op.create_table('Bookings',
    sa.Column('booking_no', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seats_booked', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("gender IN('M','F')", name='gender_check'),
    sa.ForeignKeyConstraint(['route_id'], ['Routes.route_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('booking_no')
    )
    op.create_table('Buses',
    sa.Column('bus_no', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('bus_type', sa.String(), nullable=False),
    sa.Column('Available', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("bus_type IN('AC','Non-AC')", name='bus_type_check'),
    sa.CheckConstraint('capacity BETWEEN 35 AND 40', name='capacity_check'),
    sa.ForeignKeyConstraint(['route_id'], ['Routes.route_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bus_no'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Buses')
    op.drop_table('Bookings')
    op.drop_table('Users')
    op.drop_table('Routes')
    # ### end Alembic commands ###
